'use strict';

/**
 * src/services/branding.js
 *
 * Resolves the effective branding for a report. This module is the SINGLE
 * authority on whose mark heads a PDF.
 *
 * It is a RESOLVER, not a gate. Every report at every tier is branded — there
 * is no path that returns "no branding". The fallback chain for the header
 * mark is:
 *
 *   1. the org's own logo, when its plan carries the customBranding capability
 *      AND a logo actually exists
 *   2. otherwise the CVsprings brandmark
 *
 * The previous model removed branding from unentitled orgs, which meant a free
 * report rendered with no mark at all and the absence was indistinguishable
 * from a bug. (In practice it was worse: the header mark was never implemented
 * for any tier, so `logoUrl` was resolved here and read by nobody.)
 *
 * Independently of all of the above, every report carries a provenance footer.
 * See PROVENANCE_PLATFORM — it is a hardcoded constant, unreachable by env
 * configuration and by any org field, because it is an audit artifact rather
 * than marketing and must mean the same thing on every document we emit.
 *
 * Injected values must be validated/escaped by the caller before they reach
 * HTML. This module only validates structure (URL scheme, colour shape) and
 * length; HTML-escaping happens at render time.
 */

// Entitlement is expressed ONCE, as a capability flag on the plan table.
// Nothing here compares tier names.
const { capabilitiesFor } = require('../config/plans');
const { isUnlimited } = require('./billing');
const { tintedBrandmark } = require('./brandmark');

// The product brand, NOT the operating legal entity (that is Chaulin BV, set
// via COMPANY_LEGAL_NAME and shown in terms/privacy). This name heads the
// report for orgs that have not white-labelled it.
//
// BRAND_NAME / BRAND_COLOR are read at CALL time, not captured at module load,
// so the guard against a hostile value is testable directly and so a config
// change does not need a restart to take effect.
const BRAND_NAME_FALLBACK = 'CVsprings';
const BRAND_COLOR_FALLBACK = '#0f2847';

// The legal entity must never appear as a brand on a report. BRAND_NAME is
// operator-supplied, so a misconfigured deployment could otherwise put it in
// the header; resolveBranding() rejects it below and falls back to the product
// name. Kept as a list so a rename adds a value rather than editing logic.
const LEGAL_ENTITY_NAMES = Object.freeze(['Chaulin', 'Chaulin BV', 'Chaulin B.V.']);

/**
 * The provenance footer's platform string.
 *
 * HARDCODED ON PURPOSE. Not derived from BRAND_NAME, not from
 * DEFAULT_BRAND_NAME, not from any env var, not from any org field. The footer
 * is the audit trail's answer to "what produced this document", so it has to
 * be the same string on a white-labelled Team report as on a free one — an
 * operator or a customer being able to influence it would defeat its purpose.
 */
const PROVENANCE_PLATFORM = 'Generated by CVsprings';

// Frozen so a caller cannot reach into a resolved object and blank the footer.
const PROVENANCE = Object.freeze({ platform: PROVENANCE_PLATFORM });

// Header mark box, in pdfmake points. Applied as `fit`, which scales to the
// box while preserving aspect ratio, so neither a very tall nor a very wide
// customer logo can push the title block around.
const HEADER_MARK_FIT = Object.freeze([104, 34]);

// Ink for the CVsprings mark when it sits on a dark band (the bias report's
// navy header). Pure white, matching public/brandmark-white.svg exactly.
const ON_DARK_MARK_COLOR = '#fff';

// Only http(s) absolute URLs are allowed for the logo (no data:, javascript:, etc.).
function isSafeHttpUrl(value) {
  if (typeof value !== 'string' || !value) return false;
  try {
    const u = new URL(value);
    return u.protocol === 'http:' || u.protocol === 'https:';
  } catch (_) {
    return false;
  }
}

// Accept #rgb / #rrggbb hex colours only.
function isValidColor(value) {
  return typeof value === 'string' && /^#[0-9a-fA-F]{3}([0-9a-fA-F]{3})?$/.test(value.trim());
}

function isLegalEntityName(value) {
  if (typeof value !== 'string') return false;
  const v = value.trim().toLowerCase();
  return LEGAL_ENTITY_NAMES.some((n) => n.toLowerCase() === v);
}

// The platform brand name, guarded against a deployment that has pointed
// BRAND_NAME at the legal entity. Falls back to the product name rather than
// trusting the env — a misconfigured operator cannot put "Chaulin" on a report.
function platformBrandName() {
  const configured = process.env.BRAND_NAME || BRAND_NAME_FALLBACK;
  return isLegalEntityName(configured) ? BRAND_NAME_FALLBACK : configured;
}

function platformBrandColor() {
  const configured = process.env.BRAND_COLOR || BRAND_COLOR_FALLBACK;
  return isValidColor(configured) ? configured.trim() : BRAND_COLOR_FALLBACK;
}

/**
 * Whether this org may replace the CVsprings mark with its own.
 *
 * Two conditions, deliberately separate:
 *   - the PLAN must carry the customBranding capability (src/config/plans.js)
 *   - the SUBSCRIPTION must be live, so a cancelled Pro org loses white-label
 *     on its very next report
 *
 * The capability flag alone is not sufficient: it is a property of the tier,
 * not of the org's standing on that tier. isUnlimited() supplies the second
 * half and is shared with the quota gate, so branding and quota can never
 * disagree about what a live subscription is (active, or past_due inside the
 * grace window).
 *
 * A comped org short-circuits both — that flag exists precisely for orgs with
 * no Stripe subscription to be live about.
 *
 * Fails closed: a missing or unreadable billing row is not entitled.
 */
function isCompedOrg(orgBilling) {
  if (!orgBilling) return false;
  return orgBilling.comped === 1 || orgBilling.comped === true;
}

function isEntitledToCustomBranding(orgBilling) {
  if (isCompedOrg(orgBilling)) return true;
  if (!orgBilling) return false;
  if (!capabilitiesFor(orgBilling.plan).customBranding) return false;
  return isUnlimited(orgBilling);
}

/**
 * Effective branding for a report.
 *
 * @param {object|null} orgBranding  row from getOrganizationBranding()
 * @param {object|null} orgBilling   row from getOrgBilling() — the org's CURRENT plan
 * @param {object}      [options]
 * @param {'light'|'dark'} [options.on='light']  the surface the mark lands on
 * @returns {{
 *   headerLogo: string,
 *   headerLogoType: 'svg'|'image',
 *   headerLogoFit: [number, number],
 *   surface: 'light'|'dark',
 *   needsPlate: boolean,
 *   displayName: string,
 *   isCustom: boolean,
 *   color: string,
 *   provenance: {platform: string},
 * }}
 *
 * NEVER returns null, undefined or an empty object — a report always has a
 * mark and a name to render.
 *
 * `headerLogo` is the asset itself, ready to render:
 *   headerLogoType 'svg'   -> SVG markup as a string, for a pdfmake { svg: … } node
 *   headerLogoType 'image' -> a base64 data URI, for a pdfmake { image: … } node
 * The renderer branches on the type and never assumes the two are the same
 * format.
 *
 * `options.on` is the SURFACE, not a colour. The candidate report puts the
 * mark on white; the bias report's header band is navy. Naming the context
 * rather than taking a hex keeps the presentational decision here, where the
 * mark is chosen — and it is the only form of the question that has an answer
 * for a raster logo, which cannot be recoloured at all. There is exactly one
 * asset either way: public/brandmark-white.svg is a byte-for-byte #000->#fff
 * recolour of the source, so tintedBrandmark() reproduces it. (That file stays
 * on disk for the static marketing pages, whose plain <img> cannot inherit
 * currentColor; it is simply no longer a server-render asset.)
 *
 * `needsPlate` is the signal a dark surface cannot solve on its own: an
 * uploaded raster logo in dark ink would be invisible on a dark band, and no
 * amount of tinting fixes a PNG. When true, the document should render the
 * mark on a light plate. NOTHING CONSUMES IT YET — no raster logos exist until
 * uploads land — but the condition is real and cheaper to carry now than to
 * rediscover when a customer's logo disappears.
 *
 * `displayName` is the ORG-FACING header name: the org's own when it has
 * white-labelled, the CVsprings product name otherwise. It is never the legal
 * entity, at any tier, under any BRAND_NAME. That is distinct from
 * `provenance.platform`, which is always the hardcoded CVsprings string.
 *
 * Entitlement is decided here, server-side, from the live billing row — never
 * from anything the client sends. Nothing is memoised: callers pass freshly
 * read rows and this returns a new object every time, so a plan change takes
 * effect on the very next report.
 */
function resolveBranding(orgBranding, orgBilling, options) {
  const b = orgBranding || {};
  const entitled = isEntitledToCustomBranding(orgBilling);
  // Anything that is not the string 'dark' is a light surface. Unknown values
  // fall to the default rather than throwing: a mis-typed option should not
  // take a report down.
  const surface = (options && options.on === 'dark') ? 'dark' : 'light';

  // ---- header mark: the org's own logo, else the CVsprings brandmark -------
  // Custom logos are NOT wired up yet. brandLogoUrl is a remote http(s) URL and
  // fetching it during report generation would add both an SSRF surface and an
  // uptime dependency on a third-party host, so the render path deliberately
  // stops reading it. The 'image' branch below is live and exercised by the
  // renderer; it simply has no input until uploads land (follow-up: store an
  // uploaded PNG/JPEG as a base64 data URI on the org row, magic-byte
  // validated, size-capped). Until then isCustom is false for every org.
  const customLogo = entitled ? uploadedLogoDataUri(b) : null;
  const isCustom = customLogo != null;

  const displayName = (entitled && typeof b.brandDisplayName === 'string' && b.brandDisplayName.trim()
    && !isLegalEntityName(b.brandDisplayName))
    ? b.brandDisplayName.trim().slice(0, 80)
    : platformBrandName();

  const color = (entitled && isValidColor(b.brandColor))
    ? b.brandColor.trim()
    : platformBrandColor();

  // The CVsprings mark takes the surface's ink; a customer's raster logo is
  // used as uploaded, because it cannot be recoloured.
  const markColor = surface === 'dark' ? ON_DARK_MARK_COLOR : platformBrandColor();

  return {
    headerLogo: isCustom ? customLogo : tintedBrandmark(markColor),
    headerLogoType: isCustom ? 'image' : 'svg',
    headerLogoFit: HEADER_MARK_FIT,
    surface,
    needsPlate: surface === 'dark' && isCustom,
    displayName,
    isCustom,
    color,
    provenance: PROVENANCE,
  };
}

/**
 * An org's uploaded logo as a base64 data URI, or null.
 *
 * The value is written only by the upload endpoint, which validates it by magic
 * bytes and pixel bounds first (services/fileSecurity.validateLogoUpload), so
 * anything stored here is already a PNG or JPEG within limits. The shape is
 * re-checked cheaply here anyway: this string goes straight into a server-side
 * renderer, and a row edited by hand should not reach pdfmake.
 *
 * brandLogoUrl — the old remote-URL field — is deliberately NOT consulted.
 * Fetching an org-controlled URL during report generation would add an SSRF
 * surface and an uptime dependency on a third-party host.
 */
const LOGO_DATA_URI = /^data:image\/(png|jpeg);base64,[A-Za-z0-9+/]+={0,2}$/;

function uploadedLogoDataUri(orgBranding) {
  const v = orgBranding && orgBranding.brandLogoData;
  if (typeof v !== 'string' || !v) return null;
  return LOGO_DATA_URI.test(v) ? v : null;
}

/**
 * The branding row as it may be sent to a client.
 *
 * Strips brandLogoData — it is up to ~512KB, and GET /api/auth/me runs on every
 * page load. Callers get a boolean and fetch the image itself from
 * GET /api/org/branding/logo when they actually need to show it.
 */
function publicBranding(orgBranding) {
  const b = orgBranding || {};
  return {
    brandDisplayName: b.brandDisplayName || null,
    brandColor: b.brandColor || null,
    // Retained so the UI can prompt orgs that configured the old, never-rendered
    // URL field to upload the image instead. Nothing reads it at render time.
    brandLogoUrl: b.brandLogoUrl || null,
    hasLogo: uploadedLogoDataUri(b) != null,
  };
}

module.exports = {
  BRAND_NAME_FALLBACK,
  BRAND_COLOR_FALLBACK,
  platformBrandName,
  platformBrandColor,
  LEGAL_ENTITY_NAMES,
  PROVENANCE_PLATFORM,
  HEADER_MARK_FIT,
  ON_DARK_MARK_COLOR,
  isSafeHttpUrl,
  isValidColor,
  isLegalEntityName,
  isCompedOrg,
  isEntitledToCustomBranding,
  uploadedLogoDataUri,
  publicBranding,
  resolveBranding,
};
