'use strict';

/**
 * src/services/branding.js
 *
 * Resolves the effective branding for a report. This module is the SINGLE
 * authority on whose mark heads a PDF.
 *
 * It is a RESOLVER, not a gate. Every report at every tier is branded — there
 * is no path that returns "no branding". The fallback chain for the header
 * mark is:
 *
 *   1. the org's own logo, when its plan carries the customBranding capability
 *      AND a logo actually exists
 *   2. otherwise the CVsprings brandmark
 *
 * The previous model removed branding from unentitled orgs, which meant a free
 * report rendered with no mark at all and the absence was indistinguishable
 * from a bug. (In practice it was worse: the header mark was never implemented
 * for any tier, so `logoUrl` was resolved here and read by nobody.)
 *
 * Independently of all of the above, every report carries a provenance footer.
 * See PROVENANCE_PLATFORM — it is a hardcoded constant, unreachable by env
 * configuration and by any org field, because it is an audit artifact rather
 * than marketing and must mean the same thing on every document we emit.
 *
 * Injected values must be validated/escaped by the caller before they reach
 * HTML. This module only validates structure (URL scheme, colour shape) and
 * length; HTML-escaping happens at render time.
 */

// Entitlement is expressed ONCE, as a capability flag on the plan table.
// Nothing here compares tier names.
const { capabilitiesFor } = require('../config/plans');
const { isUnlimited } = require('./billing');
const { tintedBrandmark } = require('./brandmark');

// The product brand, NOT the operating legal entity (that is Chaulin BV, set
// via COMPANY_LEGAL_NAME and shown in terms/privacy). This name heads the
// report for orgs that have not white-labelled it.
//
// BRAND_NAME / BRAND_COLOR are read at CALL time, not captured at module load,
// so the guard against a hostile value is testable directly and so a config
// change does not need a restart to take effect.
const BRAND_NAME_FALLBACK = 'CVsprings';
const BRAND_COLOR_FALLBACK = '#0f2847';

// The legal entity must never appear as a brand on a report. BRAND_NAME is
// operator-supplied, so a misconfigured deployment could otherwise put it in
// the header; resolveBranding() rejects it below and falls back to the product
// name. Kept as a list so a rename adds a value rather than editing logic.
const LEGAL_ENTITY_NAMES = Object.freeze(['Chaulin', 'Chaulin BV', 'Chaulin B.V.']);

/**
 * The provenance footer's platform string.
 *
 * HARDCODED ON PURPOSE. Not derived from BRAND_NAME, not from
 * DEFAULT_BRAND_NAME, not from any env var, not from any org field. The footer
 * is the audit trail's answer to "what produced this document", so it has to
 * be the same string on a white-labelled Team report as on a free one — an
 * operator or a customer being able to influence it would defeat its purpose.
 */
const PROVENANCE_PLATFORM = 'Generated by CVsprings';

// Frozen so a caller cannot reach into a resolved object and blank the footer.
const PROVENANCE = Object.freeze({ platform: PROVENANCE_PLATFORM });

// Header mark box, in pdfmake points. Applied as `fit`, which scales to the
// box while preserving aspect ratio, so neither a very tall nor a very wide
// customer logo can push the title block around.
const HEADER_MARK_FIT = Object.freeze([104, 34]);

// Only http(s) absolute URLs are allowed for the logo (no data:, javascript:, etc.).
function isSafeHttpUrl(value) {
  if (typeof value !== 'string' || !value) return false;
  try {
    const u = new URL(value);
    return u.protocol === 'http:' || u.protocol === 'https:';
  } catch (_) {
    return false;
  }
}

// Accept #rgb / #rrggbb hex colours only.
function isValidColor(value) {
  return typeof value === 'string' && /^#[0-9a-fA-F]{3}([0-9a-fA-F]{3})?$/.test(value.trim());
}

function isLegalEntityName(value) {
  if (typeof value !== 'string') return false;
  const v = value.trim().toLowerCase();
  return LEGAL_ENTITY_NAMES.some((n) => n.toLowerCase() === v);
}

// The platform brand name, guarded against a deployment that has pointed
// BRAND_NAME at the legal entity. Falls back to the product name rather than
// trusting the env — a misconfigured operator cannot put "Chaulin" on a report.
function platformBrandName() {
  const configured = process.env.BRAND_NAME || BRAND_NAME_FALLBACK;
  return isLegalEntityName(configured) ? BRAND_NAME_FALLBACK : configured;
}

function platformBrandColor() {
  const configured = process.env.BRAND_COLOR || BRAND_COLOR_FALLBACK;
  return isValidColor(configured) ? configured.trim() : BRAND_COLOR_FALLBACK;
}

/**
 * Whether this org may replace the CVsprings mark with its own.
 *
 * Two conditions, deliberately separate:
 *   - the PLAN must carry the customBranding capability (src/config/plans.js)
 *   - the SUBSCRIPTION must be live, so a cancelled Pro org loses white-label
 *     on its very next report
 *
 * The capability flag alone is not sufficient: it is a property of the tier,
 * not of the org's standing on that tier. isUnlimited() supplies the second
 * half and is shared with the quota gate, so branding and quota can never
 * disagree about what a live subscription is (active, or past_due inside the
 * grace window).
 *
 * A comped org short-circuits both — that flag exists precisely for orgs with
 * no Stripe subscription to be live about.
 *
 * Fails closed: a missing or unreadable billing row is not entitled.
 */
function isCompedOrg(orgBilling) {
  if (!orgBilling) return false;
  return orgBilling.comped === 1 || orgBilling.comped === true;
}

function isEntitledToCustomBranding(orgBilling) {
  if (isCompedOrg(orgBilling)) return true;
  if (!orgBilling) return false;
  if (!capabilitiesFor(orgBilling.plan).customBranding) return false;
  return isUnlimited(orgBilling);
}

/**
 * Effective branding for a report.
 *
 * @param {object|null} orgBranding  row from getOrganizationBranding()
 * @param {object|null} orgBilling   row from getOrgBilling() — the org's CURRENT plan
 * @returns {{
 *   headerLogo: string,
 *   headerLogoType: 'svg'|'image',
 *   headerLogoFit: [number, number],
 *   displayName: string,
 *   isCustom: boolean,
 *   color: string,
 *   provenance: {platform: string},
 * }}
 *
 * NEVER returns null, undefined or an empty object — a report always has a
 * mark and a name to render.
 *
 * `headerLogo` is the asset itself, ready to render:
 *   headerLogoType 'svg'   -> SVG markup as a string, for a pdfmake { svg: … } node
 *   headerLogoType 'image' -> a base64 data URI, for a pdfmake { image: … } node
 * The renderer branches on the type and never assumes the two are the same
 * format.
 *
 * `displayName` is the ORG-FACING header name: the org's own when it has
 * white-labelled, the CVsprings product name otherwise. It is never the legal
 * entity, at any tier, under any BRAND_NAME. That is distinct from
 * `provenance.platform`, which is always the hardcoded CVsprings string.
 *
 * Entitlement is decided here, server-side, from the live billing row — never
 * from anything the client sends. Nothing is memoised: callers pass freshly
 * read rows and this returns a new object every time, so a plan change takes
 * effect on the very next report.
 */
function resolveBranding(orgBranding, orgBilling) {
  const b = orgBranding || {};
  const entitled = isEntitledToCustomBranding(orgBilling);

  // ---- header mark: the org's own logo, else the CVsprings brandmark -------
  // Custom logos are NOT wired up yet. brandLogoUrl is a remote http(s) URL and
  // fetching it during report generation would add both an SSRF surface and an
  // uptime dependency on a third-party host, so the render path deliberately
  // stops reading it. The 'image' branch below is live and exercised by the
  // renderer; it simply has no input until uploads land (follow-up: store an
  // uploaded PNG/JPEG as a base64 data URI on the org row, magic-byte
  // validated, size-capped). Until then isCustom is false for every org.
  const customLogo = entitled ? uploadedLogoDataUri(b) : null;
  const isCustom = customLogo != null;

  const displayName = (entitled && typeof b.brandDisplayName === 'string' && b.brandDisplayName.trim()
    && !isLegalEntityName(b.brandDisplayName))
    ? b.brandDisplayName.trim().slice(0, 80)
    : platformBrandName();

  const color = (entitled && isValidColor(b.brandColor))
    ? b.brandColor.trim()
    : platformBrandColor();

  return {
    headerLogo: isCustom ? customLogo : tintedBrandmark(platformBrandColor()),
    headerLogoType: isCustom ? 'image' : 'svg',
    headerLogoFit: HEADER_MARK_FIT,
    displayName,
    isCustom,
    color,
    provenance: PROVENANCE,
  };
}

/**
 * An org's uploaded logo as a base64 data URI, or null.
 *
 * Always null today — there is no upload path, and the remote brandLogoUrl is
 * deliberately not fetched (see resolveBranding). Isolated as a function so the
 * follow-up that adds uploads has exactly one place to fill in, and so the
 * renderer's { image: … } branch is reachable in tests by stubbing it.
 */
function uploadedLogoDataUri(_orgBranding) {
  return null;
}

module.exports = {
  BRAND_NAME_FALLBACK,
  BRAND_COLOR_FALLBACK,
  platformBrandName,
  platformBrandColor,
  LEGAL_ENTITY_NAMES,
  PROVENANCE_PLATFORM,
  HEADER_MARK_FIT,
  isSafeHttpUrl,
  isValidColor,
  isLegalEntityName,
  isCompedOrg,
  isEntitledToCustomBranding,
  resolveBranding,
};
